server:
  port: 8003

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.sean.org.entity
  mapper-locations:
    - classpath:mybatis/mapper/*Mapper.xml

spring:
  application:
    name: servercloud-dept #一个进程（微服务）唯一的标识符，如果有多个rest controller也从该名称获得访问？
#  datasource:
#      url: jdbc:mysql://localhost:3306/cloudDB01
#      username: root
#      password: root
#      driver-class-name: com.mysql.jdbc.Driver
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://127.0.0.1:3306/cloudDB03?serverTimezone=GMT%2B8&&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: servercloud-dept8003 #显示的名称
    prefer-ip-address: true #显示Ip
info:
  app.name: sean-servercloud
  company.name: www.sean.com
  build.artifactId: provider-dept-8003
  build.version: 1.0-SNAPSHOT
