server:
  port: 7001

eureka:
  instance:
    #hostname: eureka7001.com #服务端实例名
    hostname: eureka-dev.com
  client:
    register-with-eureka: true #不注册自己
    fetch-registry: true #提供服务，不检索服务
    service-url:
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ #单机版
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/ #设置服务地址
